### ISSUE TITLE
ToolingUI: Design System v0.1.0

### ISSUE THREAD

**Issue by mcturco** [asyncapi/studio#662]
# Introduction
We would like to create a system of components that can be used for the UI in [AsyncAPI Studio](https://studio.asyncapi.com/) as well as any other future UI tools that get added into the AsyncAPI org.

There should be a range of components from a tiny scale to a large scale. The visual design of the components does not need to match any specific branding, but needs to be accessible and usable. It would be best to have a neutral color palette with one accent color.

# Task List
- [x] asyncapi/design-system#40
- [ ] **Step 2:** Ideate - Make improvements to current components & design new components
- [ ] **Step 3:** Develop - Write React components in a development environment
- [ ] **Step 4:** Test - Test components in development environment for usability
- [ ] **Step 5:** Iterate - Repeat the above steps until we are ready to release version 1
- [ ] **Step 6:** Document - Write component usage docs for both design & dev contributors

**Comment by fmvilas** [comment]
Closing as this is done on Studio now 🎉 https://github.com/asyncapi/studio/tree/master/apps/design-system

See it live on https://atoms.asyncapi.com.
